version: "3.8"

x-common: &common
  restart: always

x-values:
  labels: &labels
    traefik.enable: "true"

x-common-volume: &common-volume
  volumes:
    - "./common:/common"

services:
  traefik:
    <<: *common
    image: traefik
    ports:
      - "8080:8080"
      - "3000:80"
    command:
      --api.insecure=true
      --providers.docker
      --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  welcome:
    <<: [*common, *common-volume]
    image: ham-demo/welcome
    build:
      context: .
      dockerfile: ./app-welcome/Dockerfile
    labels:
      traefik.http.routers.welcome.rule: "PathPrefix(`/`)"
      <<: *labels


  astro:
    <<: [*common, *common-volume]
    image: ham-demo/astro
    build:
      context: .
      dockerfile: ./app-astro/Dockerfile
    labels:
      traefik.http.routers.astro.rule: "PathPrefix(`/astro`)"
      <<: *labels

  asp:
    <<: [*common, *common-volume]
    image: ham-demo/asp
    build:
      context: .
      dockerfile: ./app-asp/Dockerfile
    labels:
      traefik.http.routers.asp.rule: "PathPrefix(`/asp`)"
      <<: *labels

  assets:
    <<: [*common]
    image: pierrezemb/gostatic
    volumes:
      - "./common/public:/srv/http"
    labels:
      traefik.http.routers.assets.rule: "PathPrefix(`/assets`)"
      traefik.http.services.assets.loadbalancer.server.port: "8043"
      <<: *labels
