version: "3.8"

x-common: &common
  restart: always
  environment:
    BLOCKS_HOST: "http://common:3200/blocks"

x-values:
  labels: &labels
    traefik.enable: "true"


services:
  traefik:
    <<: *common
    image: traefik
    ports:
      - "8080:8080"
      - "3000:80"
    command:
      --api.insecure=true
      --providers.docker
      --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  welcome:
    <<: *common
    image: ham-demo/welcome
    build: ./app-welcome
    labels:
      traefik.http.routers.welcome.rule: "PathPrefix(`/`)"
      <<: *labels


  astro:
    <<: *common
    image: ham-demo/astro
    build: ./app-astro
    labels:
      traefik.http.routers.astro.rule: "PathPrefix(`/astro`)"
      <<: *labels

  common:
    <<: *common
    image: ham-demo/blocks
    build: ./common

  assets:
    <<: *common
    image: pierrezemb/gostatic
    volumes:
      - "./common/public:/srv/http"
    labels:
      traefik.http.routers.assets.rule: "PathPrefix(`/assets`)"
      traefik.http.services.assets.loadbalancer.server.port: "8043"
      <<: *labels
