version: "3.8"
services:
  traefik:
    image: traefik
    ports:
      - "8080:8080"
      - "3000:80"
    command:
      --api.insecure=true
      --providers.docker
      --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  welcome:
    image: ham-demo/welcome
    build:
      context: .
      dockerfile: ./app-welcome/Dockerfile
    volumes:
      - "./common:/common"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welcome.rule=PathPrefix(`/`)"


  astro:
    image: ham-demo/astro
    build:
      context: .
      dockerfile: ./app-astro/Dockerfile
    volumes:
      - "./common:/common"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=PathPrefix(`/astro`)"

  asp:
    image: ham-demo/asp
    build:
      context: .
      dockerfile: ./app-asp/Dockerfile
    volumes:
      - "./common:/common"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asp.rule=PathPrefix(`/asp`)"

  assets:
    image: pierrezemb/gostatic
    volumes:
      - ./common/public:/srv/http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.assets.rule=PathPrefix(`/assets`)"
      - "traefik.http.services.assets.loadbalancer.server.port=8043"
